apiVersion: apps/v1
kind: Deployment
metadata:
  name: allocation-service
spec:
  selector:
    matchLabels:
      app: allocation-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: allocation-service
    spec:
      containers:
      - image: fragg90/allocator_service:1.1.0
        name: allocation-service
        env:
        - name: spring.kafka.bootstrap-servers
          value: kafkacont:29092
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka:8762/eureka
        - name: spring.datasource.url
          valueFrom:
            configMapKeyRef:
              name: finance-manager-configmap
              key: datasource.allocation
        - name: spring.datasource.username
          valueFrom:
            configMapKeyRef:
              name: finance-manager-configmap
              key: db.user
        - name: spring.datasource.password
          valueFrom:
            configMapKeyRef:
              name: finance-manager-configmap
              key: db.password
        ports:
        - containerPort: 8066
          name: allo-service
---
apiVersion: v1
kind: Service
metadata:
  name: alloservice
spec:
  type: NodePort
  ports:
  - port: 3317
    nodePort: 30007
    targetPort: 30007
  selector:
    app: allocation-service
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: allocation-configmap 
data:
  # Configuration values can be set as key-value properties
  spring.datasource.url: jdbc:mysql://allocation-db:3307/allocation_ms_test?characterEncoding=utf8&serverTimezone=CET&createDatabaseIfNotExist=true
  spring.datasource.username: root
  spring.datasource.password: root
