name: Deploy Allocator Service

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: allocator_service

    steps:
      - name: Extract version from tag
        id: extract
        run: |
          VERSION=${GITHUB_REF##*/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check out the code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_ORG }}/allocator_service:latest
            ${{ secrets.DOCKERHUB_ORG }}/allocator_service:${{ steps.extract.outputs.version }}
          platforms: linux/arm64

      - name: Notify deploy server
        run: |
          curl -X POST https://cscherhoff.duckdns.org:3949/deploy \
            -u "${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_PASSWORD }}" \
            -H "Content-Type: application/json" \
            -d "{\"service\": \"$SERVICE_NAME\"}"
