name: Deploy Allocator Service

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: allocator_service

    steps:
      - name: Extract version from tag
        id: extract
        run: |
          VERSION=${GITHUB_REF##*/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check out the code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          IMAGE="${{ secrets.DOCKERHUB_ORG }}/$SERVICE_NAME"
          VERSION="${{ steps.extract.outputs.version }}"
          docker build -t $IMAGE:$VERSION -t $IMAGE:latest .

      - name: Push Docker image
        run: |
          IMAGE="${{ secrets.DOCKERHUB_ORG }}/$SERVICE_NAME"
          VERSION="${{ steps.extract.outputs.version }}"
          docker push $IMAGE:$VERSION
          docker push $IMAGE:latest

      - name: Notify deploy server
        run: |
          curl -X POST https://cscherhoff.duckdns.org:3949/deploy \
            -u "${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_PASSWORD }}" \
            -H "Content-Type: application/json" \
            -d "{\"service\": \"$SERVICE_NAME\"}"
