name: Deploy Microservice

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Send POST request to deploy server
        run: |
          echo "Triggering deployment..."
          response=$(curl -s -w "\n%{http_code}" -X POST https://cscherhoff.duckdns.org:3949/deploy \
            -u "${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_PASSWORD }}")
          status=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n-1)

          echo "Response status: $status"
          echo "Response body:"
          echo "$body"
